name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Vercel
      run: |
        npm i -g vercel  # Install Vercel CLI globally
        vercel --prod    # Deploy to production
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
